issue 136 solved
wietlabs/krk_meetings pull request #143
Opened 2020-10-19 17:22 UTC by tomalikem

closes #136

2020-10-19 17:27 UTC, tomekzaw requested changes

2020-10-19 17:27 UTC, tomekzaw commented on src/examples/flask_examples/example_connection.py
>      response = requests.post(URL.CONNECTION.value, json=json.dumps(query_json), timeout=1.0)
here and below again

2020-10-23 10:20 UTC, tomekzaw approved these changes

2020-10-23 10:24 UTC, merged

2020-10-23 10:24 UTC, tomalikem commented
Closes #136